name: Image Build and Publish
on: push
jobs:
  image-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: dopsdemo/vote
          tag: latest
          path: ./vote
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: dopsdemo/cache
